language: cpp
compiler:
  - gcc
  - clang

before_install:
  - sudo apt-add-repository ppa:dhart/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq pkg-config cmake cxxtest
  - test/build_dependencies.bash

before_script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug

script:
  - make all
  - make test

branches:
  except:
    - master
