language: cpp
compiler:
  - gcc
  - clang

branches:
  only:
    - develop
    - testing

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq pkg-config cmake qt4-dev-tools libqt4-dev libqt4-dbg libqjson0 libqjson-dev libqjson-dbg python-pip python lcov valgrind libzmq3-dev libzmq3-dbg libzmq3
  - sudo pip install cpp-coveralls
  - test/build_deps.sh

before_script:
  - export CMAKE_MODULE_PATH=/usr/share/apps/cmake/Modules
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug; cmake ..

script:
  - make wintermute
  - make unittest
  - make coverage
  - make memorycheck

after_success:
  - coveralls --gcov `which gcov-4.6` -r . -e .

notifications:
  email: me@jalcine.me
  on_success: change
  on_failure: always
