language: cpp
compiler:
  - gcc
  - clang

branches:
  only:
    - develop
    - testing

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq pkg-config cmake qt4-dev-tools libqt4-dev libqt4-dbg libqjson0 libqjson-dev libqjson-dbg python-pip python lcov valgrind libzmq3-dev libzmq3-dbg libzmq3
  - sudo pip install cpp-coveralls
  - test/build_deps.sh

before_script:
  - export CMAKE_MODULE_PATH=/usr/share/apps/cmake/Modules
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug; cmake ..

script:
  - make wintermute
  - make Nightly

after_success:
  - coveralls -r . -e .

notifications:
  email: me@jalcine.me
  on_success: change
  on_failure: always
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a032628cb25b35b52924
    on_success: change
    on_failure: always
    on_start: false
